image: golang:1.11.0

variables:
  REPO_NAME: gitlab.com/thundersnake/elasticwg

before_script:
  - go version
  - mkdir -p $GOPATH/src/$REPO_NAME
  - mv $CI_PROJECT_DIR/* $GOPATH/src/$REPO_NAME/
  - cd $GOPATH/src/$REPO_NAME
  - make dep

stages:
  - test
  - documentation
  - deploy

test:unittests:elastic-2.4:
  stage: test
  services:
   - name: elasticsearch:2.4
     alias: elasticsearch
  script:
    - make test

test:unittests:elastic-5:
  stage: test
  services:
    - name: elasticsearch:5
      alias: elasticsearch
  script:
    - make test

test:unittests:elastic-6.0:
  stage: test
  services:
    - name: elastic/elasticsearch:6.0.1
      alias: elasticsearch
  script:
    - make test

test:unittests:elastic-6.3:
  stage: test
  services:
    - name: elastic/elasticsearch:6.3.2
      alias: elasticsearch
  script:
    - make test

test:junit:
  stage: test
  services:
    - name: elastic/elasticsearch:6.3.2
      alias: elasticsearch
  script:
    - mkdir -p ${CI_PROJECT_DIR}/artifacts
    - make junit > ${CI_PROJECT_DIR}/artifacts/junit-report.xml
  artifacts:
    reports:
      junit: artifacts/junit-report.xml

test:lint:
  stage: test
  script:
   - make lint

doc:coverage:
  stage: documentation
  services:
    - name: elastic/elasticsearch:6.3.2
      alias: elasticsearch
  script:
    - ./ci/coverage.sh
  artifacts:
    when: on_success
    expire_in: 1 day
    paths:
    - artifacts/coverage.html

pages:
  stage: deploy
  only:
    - master
    - develop
  dependencies:
    - doc:coverage
  script:
    - mkdir -p $CI_PROJECT_DIR/public/
    - cp artifacts/coverage.html $CI_PROJECT_DIR/public/
  artifacts:
    when: on_success
    expire_in: 10 year
    paths:
     - public
