image: golang:1.10.3

variables:
  REPO_NAME: gitlab.com/thundersnake/elasticwg

before_script:
  - go version

stages:
  - test
  - documentation
  - deploy

test:unittests:elastic-2.4:
  stage: test
  services:
   - elasticsearch:2.4
  script:
    - make test

test:unittests:elastic-5:
  stage: test
  services:
    - elasticsearch:5
  script:
    - make test

test:unittests:elastic-6.0:
  stage: test
  services:
    - elastic/elasticsearch:6.0.1
  script:
    - make test

test:unittests:elastic-6.3:
  stage: test
  services:
    - elastic/elasticsearch:6.3.2
  script:
    - make test

test:junit:
  stage: test
  services:
    - elastic/elasticsearch:6.3.2
  script:
    - make junit
  artifacts:
    reports:
      junit: /go/src/${REPO_NAME}/junit-report.xml

test:lint:
  stage: test
  script:
   - make lint

doc:coverage:
  stage: documentation
  services:
    - elastic/elasticsearch:6.3.2
  script:
    - ./ci/coverage.sh
  artifacts:
    when: on_success
    expire_in: 1 day
    paths:
    - artifacts/coverage.html

pages:
  stage: deploy
  only:
    - master
  dependencies:
    - doc:coverage
  script:
    - mkdir -p $CI_PROJECT_DIR/public/
    - cp artifacts/coverage.html $CI_PROJECT_DIR/public/
  artifacts:
    when: on_success
    expire_in: 10 year
    paths:
     - public
